# Run each lines to get the output

In [13]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[7.0,6.0,5.0],[5.0,4.0,3.0]])
print(b)

[[7. 6. 5.]
 [5. 4. 3.]]


In [10]:
#get the dimension of array
#use .ndim

print("Dimension of a is",a.ndim)
print("Dimension of b is",b.ndim)

Dimension of a is 1
Dimension of b is 2


In [9]:
#get the shape of array
#use .shape

#a.shape
#b.shape


#put in a print fucntion to get both shapes, otherwise normal multiple .shape functions returns last call
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [12]:
#to get the data type
#use .dtype

print(a.dtype)
print(b.dtype)

int64
float64


## Accessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#find the shape of matrix
a.shape

(2, 7)

In [ ]:
#find specific element in matric
#you can visit items by using index of item [row,col]

#visit 13 in the array
a[1,5]

np.int64(13)

In [17]:
#get specific row
#you can use row index and ':' to get a row

a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#get specific column
#you can use ':' and column index to get a column

#visit the columb 3,10

a[: , 2 ]

array([ 3, 10])

In [ ]:
# change the number 13 to 20
#use indexing to select the number and give the value you need to change it to 
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### 3D Array


In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [27]:
#visit item in a 3D array
#you can visit items by using index of the item
# visit 6 in the array

b[1,0,1]

#6 is stay in 2nd array, 1st row,2nd col

np.int64(6)

In [30]:
#replace a array element
#Change the value of 6 into 16

b[1,0,1] = 16
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 16],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [33]:
#Change set of values

b[:,1,:] = [[9,9],[8,8],[7,7]]
b

array([[[ 1,  2],
        [ 9,  9]],

       [[ 5, 16],
        [ 8,  8]],

       [[ 9, 10],
        [ 7,  7]]])

### Initiate different types od Arrays

In [39]:
# Zero Matrix

np.zeros((2,4,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
# All 1s matrix
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [42]:
#array with any other number

np.full((2,3),23)

array([[23, 23, 23],
       [23, 23, 23]])

In [ ]:
# full_like method
#this method generate a matrix with the given matrix size and given number

np.full_like((b),12)

array([[[12, 12],
        [12, 12]],

       [[12, 12],
        [12, 12]],

       [[12, 12],
        [12, 12]]])

In [ ]:
#Array with random decimel number
# in here we dont need to give a tuple, just give the size of array

np.random.rand(4,2)

array([[0.12495935, 0.99454093],
       [0.28347463, 0.28451299],
       [0.41592768, 0.65556008],
       [0.27995314, 0.53489863]])

In [48]:
#Array with random integer
#this will generate a given size array with range of given number

np.random.randint(7,size=(4,3))

array([[1, 5, 5],
       [2, 6, 3],
       [6, 0, 1],
       [1, 3, 4]], dtype=int32)

In [49]:
#identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
#Repeat an Array

#This will generate a array with given numbers
#repeat as much as we say

arr=np.array([[3,4,5,6]])
r1 = np.repeat(arr,5,axis=0)
r1

array([[3, 4, 5, 6],
       [3, 4, 5, 6],
       [3, 4, 5, 6],
       [3, 4, 5, 6],
       [3, 4, 5, 6]])

### Print a matric like this

## 1   1   1   1   1 
## 1   0   0   0   1
## 1   0   9   0   1
## 1   0   0   0   1
## 1   1   1   1   1

In [67]:
#Set all values 1 in A
output = np.ones((5,5))

#Set the middle matrix with zeros and 9 in middle
sub_mat= np.zeros((3,3))
sub_mat[1,1]=9

#Add middle matrix into A
output[1:-1,1:-1] = sub_mat

print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
