In [2]:
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[7.0,6.0,5.0],[5.0,4.0,3.0]])
print(b)

[[7. 6. 5.]
 [5. 4. 3.]]


In [10]:
#get the dimension of array
#use .ndim

print("Dimension of a is",a.ndim)
print("Dimension of b is",b.ndim)

Dimension of a is 1
Dimension of b is 2
