# NumPy 

In [3]:
import numpy as np

In [ ]:
#Check numpy version
print(np.__version__)

2.5.3


In [3]:
#multiply number list by a number

array = np.array([2,3,5,6])

array = array * 2

print(array)

[ 4  6 10 12]


## Multidimensional Arrays

### 2D Array

In [13]:
# Create a 2D Array

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]) 

print(array)

# Check the dimension
print(array.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


### 3D Array

In [12]:
# Create a 3D Array

array = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

print(array)

# Check the dimension
print(array.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
3


## Slicing

Slicing is the way to access elements in array

In [4]:
array = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

```text
array= [[ 1  2  3  4]
        [ 5  6  7  8]
        [ 9 10 11 12]
        [13 14 15 16]]

```

To access items we can use 
##### > array[start : end : stepsize]

In [5]:
# Get the numbers in 1st row

row1= array[0]
print(row1)

[1 2 3 4]


In [10]:
# Get row 1 and 3
row1_3 = array[0:4:2]
print(row1_3)

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [11]:
# Get last row

row4 = array[-1]
print(row4)

[13 14 15 16]


In [12]:
# Get row 1 column 1

row1_col1 = array[0,0]
print(row1_col1)

1


In [13]:
# Get row 2 column 3
row2_col3 = array[1,2]
print(row2_col3)

7


In [ ]:
# Get all rows column 2

col2 = array[:,1]
print(col2)

[ 2  6 10 14]


In [15]:
# Get row 1 & 2, column 3

row1_2_col3 = array[0:2,2]
print(row1_2_col3)

[3 7]


In [16]:
# Get column 3

col3 = array [: ,-2]
print(col3)

[ 3  7 11 15]


## Arithmetics

Scalar Arithmetics

In [ ]:
array = np.array([1,2,3])

print(array +1)
print(array -2)
print(array *3)
print(array /4)
print(array ** 3)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[ 1  8 27]


Vectorized operations

In [ ]:
array = np.array([1,2,3])
print(np.sqrt(array))


In [25]:
array = np.array([1.05,2.45,3.98])

# Round values
print(np.round(array))

# Set to floor
print(np.floor(array))

# Set to ceiling
print(np.ceil(array))


[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]


Element-wise arithmetics

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

sum = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2
power = arr1 ** arr2

print(sum)
print(sub)
print(mul)
print(div)
print(power)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
