# NumPy 

In [ ]:
import numpy as np

In [ ]:
#Check numpy version
print(np.__version__)

In [ ]:
#multiply number list by a number

array = np.array([2,3,5,6])

array = array * 2

print(array)

## Multidimensional Arrays

### 2D Array

In [ ]:
# Create a 2D Array

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]) 

print(array)

# Check the dimension
print(array.ndim)

### 3D Array

In [ ]:
# Create a 3D Array

array = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

print(array)

# Check the dimension
print(array.ndim)

## Slicing

Slicing is the way to access elements in array

In [ ]:
array = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

```text
array= [[ 1  2  3  4]
        [ 5  6  7  8]
        [ 9 10 11 12]
        [13 14 15 16]]

```

To access items we can use 
##### > array[start : end : stepsize]

In [ ]:
# Get the numbers in 1st row

row1= array[0]
print(row1)

In [ ]:
# Get row 1 and 3
row1_3 = array[0:4:2]
print(row1_3)

In [ ]:
# Get last row

row4 = array[-1]
print(row4)

In [ ]:
# Get row 1 column 1

row1_col1 = array[0,0]
print(row1_col1)

In [ ]:
# Get row 2 column 3
row2_col3 = array[1,2]
print(row2_col3)

In [ ]:
# Get all rows column 2

col2 = array[:,1]
print(col2)

In [ ]:
# Get row 1 & 2, column 3

row1_2_col3 = array[0:2,2]
print(row1_2_col3)

In [ ]:
# Get column 3

col3 = array [: ,-2]
print(col3)

## Arithmetics

Scalar Arithmetics

In [ ]:
array = np.array([1,2,3])

print(array +1)
print(array -2)
print(array *3)
print(array /4)
print(array ** 3)

Vectorized operations

In [ ]:
array = np.array([1,2,3])
print(np.sqrt(array))


In [ ]:
array = np.array([1.05,2.45,3.98])

# Round values
print(np.round(array))

# Set to floor
print(np.floor(array))

# Set to ceiling
print(np.ceil(array))


Element-wise arithmetics

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

sum = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2
power = arr1 ** arr2

print(sum)
print(sub)
print(mul)
print(div)
print(power)

## Broadcasting

Broadcasting is a NumPy feature that allows operations between arrays with different shapes.

NumPy automatically adjusts the shapes when the arrays are compatible.

In [ ]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1 * array2)



### Broadcasting Rules

There are 3 main rules to remember.

#### Rule 1 — Compare Dimensions from Right to Left

When comparing two array shapes, start from the rightmost dimension and move toward the left.

Example:

A = (3, 4)
B = (4,)

Align the shapes from the right:

A = (3, 4)
B = (   4)

The 4 dimensions match, so they are compatible.

#### Rule 2 — Dimensions Are Compatible When They Are Equal

Two dimensions are compatible when they have the same size.

3 vs 3 → Compatible
4 vs 4 → Compatible
5 vs 5 → Compatible

Example:

A = (3, 4)
B = (3, 4)

The shapes are compatible.

#### Rule 3 — A Dimension of 1 Can Be Broadcast

Two dimensions are also compatible when one of them is 1.

3 vs 1 → Compatible
4 vs 1 → Compatible
1 vs 5 → Compatible

Example:

A = (3, 4)
B = (3, 1)

Compare from right to left:

4 vs 1 → Compatible
3 vs 3 → Compatible

Therefore, broadcasting is possible.

=========================================
#### When Does Broadcasting Fail?

Broadcasting fails when two corresponding dimensions are:

Different
Neither dimension is 1

Example:

A = (3, 4)
B = (3, 2)

Compare from right to left:

4 vs 2 → Not compatible

Therefore:

❌ Broadcasting is not possible

========================================

## Aggregate Functions

Aggregate functions summerizes data and typically return a single value

In [ ]:
array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

sum_of_values_in_array = np.sum(array)
print(f"Sum = {sum_of_values_in_array}")

average_of_values_in_array = np.mean(array)
print(f"Average = {average_of_values_in_array}")

standard_deviation_of_values = np.std(array)
print(f"Standard Deviation = {standard_deviation_of_values}")

variance_of_values = np.var(array)
print(f"Variance = {standard_deviation_of_values}")

In [ ]:
minimum_value_in_array = np.min(array)
print(f"Minimum = {minimum_value_in_array}")

maximum_value_in_array = np.max(array)
print(f"Maximum = {maximum_value_in_array}")

position_of_min_value = np.argmin(array)
print(f"Position of Minimum = {position_of_min_value}")

position_of_max_value = np.argmax(array)
print(f"Position of Maximum = {position_of_max_value}")


We can apply these functions to row wise or column wise

In [ ]:
# sum of values in array, column wise
print(f"Sum of Columns = {np.sum(array , axis =0)}")

# sum of values in array, row wise
print(f"Sum of Rows = {np.sum(array , axis =1)}")



## Filtering

In [ ]:
ages = np.array([
    [16,23,45,27,58,36,42],
    [17,43,23,25,67,45,15]
])

teenagers = ages[ages<65]

middleagers = ages[(ages>18) & (ages<50)]



print(middleagers)

#### np.where()

np.where() is a NumPy function used to select elements or find their indices based on a specified condition

The easiest way to understand np.where() is:

"Check a condition. If it's True, take this value; if it's False, take that value."

In [ ]:
adults = np.where(ages >=18 , ages, 0) 
# Check for the condition if it is True use the age, if False use 0
print(adults)

## Random Numbers

A random number generator (RNG) is a tool that produces numbers that appear unpredictable.

In [ ]:
rng = np.random.default_rng()

random = rng.integers(1,7)
# Generate a random number between 1-6
print(random)

In [ ]:
random = rng.integers(low=1, high=101,size=3)
# Generate "3" numbers between 1-100
print(random)

In [ ]:
rand_matrix = rng.integers(low = 1, high= 101, size=(3,2))
# Generate a '3x2' matrix with random numbers
print(rand_matrix)

In [ ]:
# Shuffle method

array = np.array([1,2,3,4,5])
rng.shuffle(array) # Shuffle method is use to shuffle numbers in array
print(array)

In [ ]:
# Choice method

fruits = np.array(["apple","orange","banana","pineapple","grapes"])
fruit =rng.choice(fruits)
print(fruit)

In [ ]:
rng = np.random.default_rng(seed=1)

rand_matrix = rng.integers(low = 1, high= 101, size=(3,2))
print(rand_matrix)
